env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[5973020200:AAGnzOj19i4FzMjKYwJKQpDmBiQThIie9w4]
    TG_TOKEN: ENCRYPTED[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]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/cumaRull/OrangeFox-Cirrus-CI/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/cumaRull/OrangeFox-Cirrus-CI/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/cumaRull/OrangeFox-Cirrus-CI/main/scripts/upload.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/cumaRull/OrangeFox-Cirrus-CI/main/scripts/upload.sh)"
