env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Device
    FOX_BRANCH: fox_9.0
    DT_LINK: https://github.com/Azure-007/android_device_xiaomi_raphael-ofox.git -b a11fw
    DEVICE: raphael
    OEM: xiaomi
    TARGET: recoveryimage

    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: OrangeFox*.zip

    # Extra Command
    EXTRA_CMD: git clone https://github.com/OrangeFoxRecovery/Avatar.git misc

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Full (absolute) path. Use "$HOME" instead of "~".
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

    # Telegram
    TG_CHAT_ID: -1001223945191
    TG_TOKEN: 5142076608:AAG4kk4owwAfwszKboyyGj0S2uRQCDJHNBQ

task:
  name: "Recovery Build"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash upload.sh
