task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
  
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git config --global user.name "atharv2951"
       - git config --global user.email "atharv2951@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Neofetch_script:
       - neofetch
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir ~/OrangeFox_sync
      - cd ~/OrangeFox_sync
      - git clone https://gitlab.com/OrangeFox/sync.git
      - cd sync
      - ./orangefox_sync.sh --branch 10.0 --path ~/fox_10.0
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"
  
  Clone-OrangeFox-Theme_script:
      - cd ~
      - cd fox_10.0
      - git clone https://github.com/Atharv2951-Roms/recovery_device_samsung_m11q device/samsung/m11q
      - rm -rf bootable/recovery vendor/recovery
      - git clone https://gitlab.com/OrangeFox/bootable/Recovery.git -b fox_10.0 bootable/recovery
      - git clone https://gitlab.com/OrangeFox/vendor/recovery.git -b fox_10.0 vendor/recovery
      - git clone https://gitlab.com/OrangeFox/misc/Theme.git bootable/recovery/gui/theme
  
  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export LC_ALL="C"
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch omni_m11q-eng
      - mka recoveryimage
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~
      - cd fox_10.0
      - cd out/target/product/m11q
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file O*.zip https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

