version: 2.1

jobs:
  build:
    shell: /bin/bash -eo pipefail
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
    resource_class: large
    parallelism: 4
    environment:
      # OrangeFox Sync Repository
      FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
      # Config
      CONFIG: config.sh
      # Telegram
      TG_CHAT_ID: ENCRYPTED[0003e1cf5276424a5b2afb8c6a39f2d830864e8555b37220bd3bf173f3ef5b8769ab98425d96a76adf64b18241c940dd]
      TG_TOKEN: ENCRYPTED[03de4105db5d23ec42490965c0a0f79217c1e3366cb152bd9d9a045e22586eba675615e1f08bf1aea3e860d499efde60]

    steps:
     
    - checkout
    
    - run:
         name: Checks_script
         command: curl -sL https://raw.githubusercontent.com/Diwas1111/OrangeFox-CI/main/scripts/checks.sh | bash
     
    - run:
        name: Sync_script
        command: curl -sL https://raw.githubusercontent.com/Diwas1111/OrangeFox-CI/main/scripts/sync.sh | bash
     
    - run:
        name: Build_script
        command: curl -sL https://raw.githubusercontent.com/Diwas1111/OrangeFox-CI/main/scripts/build.sh | bash
     
    - run:
        name: Upload_script
        command: |
              export TIMEOUT=43200 # Link timeout (in minutes)
              curl -sL https://raw.githubusercontent.com/Diwas1111/OrangeFox-CI/main/scripts/upload.sh | bash
