name: OrangeFox ROM Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5 libncurses5:i386 \
          zlib1g zlib1g:i386 g++-multilib git-core gnupg flex bison gperf \
          build-essential zip curl libc6-dev libncurses5-dev:i386 \
          x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 \
          libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib \
          libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
          libgl1-mesa-dev g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev:i386 \
          libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev \
          g++-multilib libc6-dev-i386 lib32ncurses5-dev \
          x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 \
          libgl1-mesa-glx:i386 libgl1-mesa-dev

    - name: Clone Orange Fox Repository
      run: |
        git clone https://github.com/OrangeFoxRecovery/manifest.git fox
        cd fox
        repo init -u https://gitlab.com/OrangeFox/Manifest.git -b fox_10.0
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Build Orange Fox
      run: |
        cd fox
        . build/envsetup.sh
        lunch omni_codename-eng # replace 'codename' with your device codename
        make recoveryimage

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: OrangeFox-Recovery
        path: out/target/product/codename/recovery.img # replace 'codename' with your device codename
