name: OrangeFox ROM Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Dependencies
      run: |
      sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Clone Orange Fox Repository
      run: |
        git clone https://github.com/OrangeFoxRecovery/manifest.git fox
        cd fox
        repo init -u https://gitlab.com/OrangeFox/Manifest.git -b fox_10.0
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Build Orange Fox
      run: |
        cd fox
        . build/envsetup.sh
        lunch omni_lancelot-eng # replace 'codename' with your device codename
        make recoveryimage

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: OrangeFox-Recovery
        path: out/target/product/codename/recovery.img # replace 'codename' with your device codename
